// Generated by tools/gen_family_fixtures.py using embit 0.8.0 and bip_utils 2.12.2.
// BIP-39 12-word vector: https://github.com/bitcoin/bips/blob/master/bip-0039.mediawiki
// BIP-39 24-word vector 8: https://github.com/trezor/python-mnemonic/blob/master/vectors.json
// Mainstream wallet paths are documented in the generator's source comments.
#pragma once
#include <stddef.h>
#include <stdint.h>
#include "coin_catalog.h"

static const uint8_t family_seed_bip39_12[] = {
    0x5e, 0xb0, 0x0b, 0xbd, 0xdc, 0xf0, 0x69, 0x08, 0x48, 0x89, 0xa8, 0xab,
    0x91, 0x55, 0x56, 0x81, 0x65, 0xf5, 0xc4, 0x53, 0xcc, 0xb8, 0x5e, 0x70,
    0x81, 0x1a, 0xae, 0xd6, 0xf6, 0xda, 0x5f, 0xc1, 0x9a, 0x5a, 0xc4, 0x0b,
    0x38, 0x9c, 0xd3, 0x70, 0xd0, 0x86, 0x20, 0x6d, 0xec, 0x8a, 0xa6, 0xc4,
    0x3d, 0xae, 0xa6, 0x69, 0x0f, 0x20, 0xad, 0x3d, 0x8d, 0x48, 0xb2, 0xd2,
    0xce, 0x9e, 0x38, 0xe4
};

static const uint8_t family_seed_bip39_24[] = {
    0x40, 0x8b, 0x28, 0x5c, 0x12, 0x38, 0x36, 0x00, 0x4f, 0x4b, 0x88, 0x42,
    0xc8, 0x93, 0x24, 0xc1, 0xf0, 0x13, 0x82, 0x45, 0x0c, 0x0d, 0x43, 0x9a,
    0xf3, 0x45, 0xba, 0x7f, 0xc4, 0x9a, 0xcf, 0x70, 0x54, 0x89, 0xc6, 0xfc,
    0x77, 0xdb, 0xd4, 0xe3, 0xdc, 0x1d, 0xd8, 0xcc, 0x6b, 0xc9, 0xf0, 0x43,
    0xdb, 0x8a, 0xda, 0x1e, 0x24, 0x3c, 0x4a, 0x0e, 0xaf, 0xb2, 0x90, 0xd3,
    0x99, 0x48, 0x08, 0x40
};

static const uint8_t family_seed_bip39_12_trezor[] = {
    0xc5, 0x52, 0x57, 0xc3, 0x60, 0xc0, 0x7c, 0x72, 0x02, 0x9a, 0xeb, 0xc1,
    0xb5, 0x3c, 0x05, 0xed, 0x03, 0x62, 0xad, 0xa3, 0x8e, 0xad, 0x3e, 0x3e,
    0x9e, 0xfa, 0x37, 0x08, 0xe5, 0x34, 0x95, 0x53, 0x1f, 0x09, 0xa6, 0x98,
    0x75, 0x99, 0xd1, 0x82, 0x64, 0xc1, 0xe1, 0xc9, 0x2f, 0x2c, 0xf1, 0x41,
    0x63, 0x0c, 0x7a, 0x3c, 0x4a, 0xb7, 0xc8, 0x1b, 0x2f, 0x00, 0x16, 0x98,
    0xe7, 0x46, 0x3b, 0x04
};

typedef struct {
    WalletFamily family;
    const char *family_name;
    const char *derivation_path;
    const char *reference_wallet;
    const char *reference_implementation;
    const char *mnemonic_case;
    const uint8_t *seed;
    const char *reference_address;
    const char *mainstream_wallet_address;
} FamilyAddressFixture;

static const FamilyAddressFixture family_address_fixtures[] = {
    {FAM_BTC, "BTC", "m/84'/0'/0'/0/0", "Trust Wallet (BIP84 default)", "embit BIP84", "BIP-39 12-word official vector, empty passphrase", family_seed_bip39_12, "bc1qcr8te4kr609gcawutmrza0j4xv80jy8z306fyu", "bc1qcr8te4kr609gcawutmrza0j4xv80jy8z306fyu"},
    {FAM_EVM, "EVM", "m/44'/60'/0'/0/0", "Trust Wallet / MetaMask EVM default", "bip_utils Ethereum", "BIP-39 12-word official vector, empty passphrase", family_seed_bip39_12, "0x9858EfFD232B4033E47d90003D41EC34EcaEda94", "0x9858EfFD232B4033E47d90003D41EC34EcaEda94"},
    {FAM_SOL, "SOL", "m/44'/501'/0'/0'", "Phantom bip44Change account 0", "bip_utils Solana", "BIP-39 12-word official vector, empty passphrase", family_seed_bip39_12, "HAgk14JpMQLgt6rVgv7cBQFJWFto5Dqxi472uT3DKpqk", "HAgk14JpMQLgt6rVgv7cBQFJWFto5Dqxi472uT3DKpqk"},
    {FAM_DOGE, "DOGE", "m/44'/3'/0'/0/0", "Trust Wallet default", "bip_utils Dogecoin", "BIP-39 12-word official vector, empty passphrase", family_seed_bip39_12, "DBus3bamQjgJULBJtYXpEzDWQRwF5iwxgC", "DBus3bamQjgJULBJtYXpEzDWQRwF5iwxgC"},
    {FAM_LTC, "LTC", "m/84'/2'/0'/0/0", "Trust Wallet SegWit default", "bip_utils BIP84 Litecoin", "BIP-39 12-word official vector, empty passphrase", family_seed_bip39_12, "ltc1qjmxnz78nmc8nq77wuxh25n2es7rzm5c2rkk4wh", "ltc1qjmxnz78nmc8nq77wuxh25n2es7rzm5c2rkk4wh"},
    {FAM_TRX, "TRX", "m/44'/195'/0'/0/0", "Trust Wallet default", "bip_utils TRON", "BIP-39 12-word official vector, empty passphrase", family_seed_bip39_12, "TUEZSdKsoDHQMeZwihtdoBiN46zxhGWYdH", "TUEZSdKsoDHQMeZwihtdoBiN46zxhGWYdH"},
    {FAM_XRP, "XRP", "m/44'/144'/0'/0/0", "Trust Wallet default; same SLIP-44 path", "bip_utils Ripple", "BIP-39 12-word official vector, empty passphrase", family_seed_bip39_12, "rHsMGQEkVNJmpGWs8XUBoTBiAAbwxZN5v3", "rHsMGQEkVNJmpGWs8XUBoTBiAAbwxZN5v3"},
    {FAM_ATOM, "ATOM", "m/44'/118'/0'/0/0", "Keplr Cosmos Hub default", "bip_utils Cosmos", "BIP-39 12-word official vector, empty passphrase", family_seed_bip39_12, "cosmos19rl4cm2hmr8afy4kldpxz3fka4jguq0auqdal4", "cosmos19rl4cm2hmr8afy4kldpxz3fka4jguq0auqdal4"},
    {FAM_INJ, "INJ", "m/44'/60'/0'/0/0", "Keplr Injective coin type 60", "bip_utils Injective", "BIP-39 12-word official vector, empty passphrase", family_seed_bip39_12, "inj1npvwllfr9dqr8erajqqr6s0vxnk2ak55re90dz", "inj1npvwllfr9dqr8erajqqr6s0vxnk2ak55re90dz"},
    {FAM_VET, "VET", "m/44'/818'/0'/0/0", "Trust Wallet Wallet Core default", "bip_utils VeChain", "BIP-39 12-word official vector, empty passphrase", family_seed_bip39_12, "0xE5d846748409dF0b23D5bd47CEB14afc1CBbbcB3", "0xE5d846748409dF0b23D5bd47CEB14afc1CBbbcB3"},
    {FAM_BCH, "BCH", "m/44'/145'/0'/0/0", "Trust Wallet default", "bip_utils Bitcoin Cash", "BIP-39 12-word official vector, empty passphrase", family_seed_bip39_12, "bitcoincash:qqyx49mu0kkn9ftfj6hje6g2wfer34yfnq5tahq3q6", "bitcoincash:qqyx49mu0kkn9ftfj6hje6g2wfer34yfnq5tahq3q6"},
    {FAM_ZEC, "ZEC", "m/44'/133'/0'/0/0", "Exodus transparent t-address path", "bip_utils Zcash", "BIP-39 12-word official vector, empty passphrase", family_seed_bip39_12, "t1XVXWCvpMgBvUaed4XDqWtgQgJSu1Ghz7F", "t1XVXWCvpMgBvUaed4XDqWtgQgJSu1Ghz7F"},
    {FAM_XLM, "XLM", "m/44'/148'/0'", "Freighter / Stellar SEP-0005 account path", "bip_utils Stellar", "BIP-39 12-word official vector, empty passphrase", family_seed_bip39_12, "GB3JDWCQJCWMJ3IILWIGDTQJJC5567PGVEVXSCVPEQOTDN64VJBDQBYX", "GB3JDWCQJCWMJ3IILWIGDTQJJC5567PGVEVXSCVPEQOTDN64VJBDQBYX"},
    {FAM_NEAR, "NEAR", "m/44'/397'/0'", "SafePal NEAR path", "bip_utils NEAR Protocol", "BIP-39 12-word official vector, empty passphrase", family_seed_bip39_12, "5510e2b44cae6eb807e3e0e45d579dda058c274abcba15e5cb84636f5d1ee412", "5510e2b44cae6eb807e3e0e45d579dda058c274abcba15e5cb84636f5d1ee412"},
    {FAM_APT, "APT", "m/44'/637'/0'/0'/0'", "Petra-compatible Aptos Ed25519 path", "bip_utils Aptos", "BIP-39 12-word official vector, empty passphrase", family_seed_bip39_12, "0xeb663b681209e7087d681c5d3eed12aaa8e1915e7c87794542c3f96e94b3d3bf", "0xeb663b681209e7087d681c5d3eed12aaa8e1915e7c87794542c3f96e94b3d3bf"},
    {FAM_SUI, "SUI", "m/44'/784'/0'/0'/0'", "Sui Wallet Ed25519 path", "bip_utils Sui", "BIP-39 12-word official vector, empty passphrase", family_seed_bip39_12, "0x5e93a736d04fbb25737aa40bee40171ef79f65fae833749e3c089fe7cc2161f1", "0x5e93a736d04fbb25737aa40bee40171ef79f65fae833749e3c089fe7cc2161f1"},
    {FAM_BTC, "BTC", "m/84'/0'/0'/0/0", "Trust Wallet (BIP84 default)", "embit BIP84", "BIP-39 24-word official vector 8, empty passphrase", family_seed_bip39_24, "bc1qzmtrqsfuaf6l6kkcsseumq26ukaphfj9skkug6", "bc1qzmtrqsfuaf6l6kkcsseumq26ukaphfj9skkug6"},
    {FAM_EVM, "EVM", "m/44'/60'/0'/0/0", "Trust Wallet / MetaMask EVM default", "bip_utils Ethereum", "BIP-39 24-word official vector 8, empty passphrase", family_seed_bip39_24, "0xF278cF59F82eDcf871d630F28EcC8056f25C1cdb", "0xF278cF59F82eDcf871d630F28EcC8056f25C1cdb"},
    {FAM_SOL, "SOL", "m/44'/501'/0'/0'", "Phantom bip44Change account 0", "bip_utils Solana", "BIP-39 24-word official vector 8, empty passphrase", family_seed_bip39_24, "3Cy3YNTFywCmxoxt8n7UH6hg6dLo5uACowX3CFceaSnx", "3Cy3YNTFywCmxoxt8n7UH6hg6dLo5uACowX3CFceaSnx"},
    {FAM_DOGE, "DOGE", "m/44'/3'/0'/0/0", "Trust Wallet default", "bip_utils Dogecoin", "BIP-39 24-word official vector 8, empty passphrase", family_seed_bip39_24, "DL1DoPj4HvpnRT9n3YfCkhHXe5287wMyWD", "DL1DoPj4HvpnRT9n3YfCkhHXe5287wMyWD"},
    {FAM_LTC, "LTC", "m/84'/2'/0'/0/0", "Trust Wallet SegWit default", "bip_utils BIP84 Litecoin", "BIP-39 24-word official vector 8, empty passphrase", family_seed_bip39_24, "ltc1qj0xmcw3ttxgsfhzzcft9ac9nwp8smzq778lu3c", "ltc1qj0xmcw3ttxgsfhzzcft9ac9nwp8smzq778lu3c"},
    {FAM_TRX, "TRX", "m/44'/195'/0'/0/0", "Trust Wallet default", "bip_utils TRON", "BIP-39 24-word official vector 8, empty passphrase", family_seed_bip39_24, "TEfhiqsW1SdN44DeHrAWVmbyr8ZbvChrtS", "TEfhiqsW1SdN44DeHrAWVmbyr8ZbvChrtS"},
    {FAM_XRP, "XRP", "m/44'/144'/0'/0/0", "Trust Wallet default; same SLIP-44 path", "bip_utils Ripple", "BIP-39 24-word official vector 8, empty passphrase", family_seed_bip39_24, "rKxpJQ6hLWYbo7p1oo7WHjrcrRFv1TUQeC", "rKxpJQ6hLWYbo7p1oo7WHjrcrRFv1TUQeC"},
    {FAM_ATOM, "ATOM", "m/44'/118'/0'/0/0", "Keplr Cosmos Hub default", "bip_utils Cosmos", "BIP-39 24-word official vector 8, empty passphrase", family_seed_bip39_24, "cosmos1r5v5srda7xfth3hn2s26txvrcrntldjumt8mhl", "cosmos1r5v5srda7xfth3hn2s26txvrcrntldjumt8mhl"},
    {FAM_INJ, "INJ", "m/44'/60'/0'/0/0", "Keplr Injective coin type 60", "bip_utils Injective", "BIP-39 24-word official vector 8, empty passphrase", family_seed_bip39_24, "inj17fuv7k0c9mw0suwkxreganyq2me9c8xmna9hem", "inj17fuv7k0c9mw0suwkxreganyq2me9c8xmna9hem"},
    {FAM_VET, "VET", "m/44'/818'/0'/0/0", "Trust Wallet Wallet Core default", "bip_utils VeChain", "BIP-39 24-word official vector 8, empty passphrase", family_seed_bip39_24, "0x61520D420149ED6B81820F6B2d116676b0cd4a37", "0x61520D420149ED6B81820F6B2d116676b0cd4a37"},
    {FAM_BCH, "BCH", "m/44'/145'/0'/0/0", "Trust Wallet default", "bip_utils Bitcoin Cash", "BIP-39 24-word official vector 8, empty passphrase", family_seed_bip39_24, "bitcoincash:qzlpu4vqftmmufrt2zvh8v2l8kskjuwllcmx6mydzm", "bitcoincash:qzlpu4vqftmmufrt2zvh8v2l8kskjuwllcmx6mydzm"},
    {FAM_ZEC, "ZEC", "m/44'/133'/0'/0/0", "Exodus transparent t-address path", "bip_utils Zcash", "BIP-39 24-word official vector 8, empty passphrase", family_seed_bip39_24, "t1dUDJ62ANtmebE8drFg7g2MWYwXHQ6Xu3F", "t1dUDJ62ANtmebE8drFg7g2MWYwXHQ6Xu3F"},
    {FAM_XLM, "XLM", "m/44'/148'/0'", "Freighter / Stellar SEP-0005 account path", "bip_utils Stellar", "BIP-39 24-word official vector 8, empty passphrase", family_seed_bip39_24, "GB3TCCIC6KLYKM72PX7KA6RNYC2BHC7DQYDMEAAN7PDMUZQD7UKJGSSY", "GB3TCCIC6KLYKM72PX7KA6RNYC2BHC7DQYDMEAAN7PDMUZQD7UKJGSSY"},
    {FAM_NEAR, "NEAR", "m/44'/397'/0'", "SafePal NEAR path", "bip_utils NEAR Protocol", "BIP-39 24-word official vector 8, empty passphrase", family_seed_bip39_24, "5cd11aa446d8db56ace1bd3781673e351af6481b86c4660a8acd424973f9827b", "5cd11aa446d8db56ace1bd3781673e351af6481b86c4660a8acd424973f9827b"},
    {FAM_APT, "APT", "m/44'/637'/0'/0'/0'", "Petra-compatible Aptos Ed25519 path", "bip_utils Aptos", "BIP-39 24-word official vector 8, empty passphrase", family_seed_bip39_24, "0x226b5b5c15d19946b1fd26c3e4ad36833fd8c9c11c612b1327e608f824a5f2d4", "0x226b5b5c15d19946b1fd26c3e4ad36833fd8c9c11c612b1327e608f824a5f2d4"},
    {FAM_SUI, "SUI", "m/44'/784'/0'/0'/0'", "Sui Wallet Ed25519 path", "bip_utils Sui", "BIP-39 24-word official vector 8, empty passphrase", family_seed_bip39_24, "0xf967e21c16a4757daafec13ee79c0dc5c5329199be5d70c86fd07b8e75db892c", "0xf967e21c16a4757daafec13ee79c0dc5c5329199be5d70c86fd07b8e75db892c"},
    {FAM_BTC, "BTC", "m/84'/0'/0'/0/0", "Trust Wallet (BIP84 default)", "embit BIP84", "BIP-39 12-word vector with passphrase TREZOR", family_seed_bip39_12_trezor, "bc1qv5rmq0kt9yz3pm36wvzct7p3x6mtgehjul0feu", "bc1qv5rmq0kt9yz3pm36wvzct7p3x6mtgehjul0feu"},
    {FAM_EVM, "EVM", "m/44'/60'/0'/0/0", "Trust Wallet / MetaMask EVM default", "bip_utils Ethereum", "BIP-39 12-word vector with passphrase TREZOR", family_seed_bip39_12_trezor, "0x9c32F71D4DB8Fb9e1A58B0a80dF79935e7256FA6", "0x9c32F71D4DB8Fb9e1A58B0a80dF79935e7256FA6"},
    {FAM_SOL, "SOL", "m/44'/501'/0'/0'", "Phantom bip44Change account 0", "bip_utils Solana", "BIP-39 12-word vector with passphrase TREZOR", family_seed_bip39_12_trezor, "7zSmbu6gKkb6HB7UDPtHYjwCWuBHU1D4TpNZFm4sndQe", "7zSmbu6gKkb6HB7UDPtHYjwCWuBHU1D4TpNZFm4sndQe"},
    {FAM_DOGE, "DOGE", "m/44'/3'/0'/0/0", "Trust Wallet default", "bip_utils Dogecoin", "BIP-39 12-word vector with passphrase TREZOR", family_seed_bip39_12_trezor, "DMn7J63QSZUR9XNxsUJtvsttZVzV9Am4qM", "DMn7J63QSZUR9XNxsUJtvsttZVzV9Am4qM"},
    {FAM_LTC, "LTC", "m/84'/2'/0'/0/0", "Trust Wallet SegWit default", "bip_utils BIP84 Litecoin", "BIP-39 12-word vector with passphrase TREZOR", family_seed_bip39_12_trezor, "ltc1qmnmdtk82gfvv4khc3w9lrugre34cj65kamf9tz", "ltc1qmnmdtk82gfvv4khc3w9lrugre34cj65kamf9tz"},
    {FAM_TRX, "TRX", "m/44'/195'/0'/0/0", "Trust Wallet default", "bip_utils TRON", "BIP-39 12-word vector with passphrase TREZOR", family_seed_bip39_12_trezor, "TAyDUYP5rcf56xFwrg8cU1qQwvnWpkeapM", "TAyDUYP5rcf56xFwrg8cU1qQwvnWpkeapM"},
    {FAM_XRP, "XRP", "m/44'/144'/0'/0/0", "Trust Wallet default; same SLIP-44 path", "bip_utils Ripple", "BIP-39 12-word vector with passphrase TREZOR", family_seed_bip39_12_trezor, "rfBUajJsZotvNwZz5yUk7GNqcWehxc2YAs", "rfBUajJsZotvNwZz5yUk7GNqcWehxc2YAs"},
    {FAM_ATOM, "ATOM", "m/44'/118'/0'/0/0", "Keplr Cosmos Hub default", "bip_utils Cosmos", "BIP-39 12-word vector with passphrase TREZOR", family_seed_bip39_12_trezor, "cosmos12fdxecq3dp28aaswp2n3yk35p782g3w9dz32m6", "cosmos12fdxecq3dp28aaswp2n3yk35p782g3w9dz32m6"},
    {FAM_INJ, "INJ", "m/44'/60'/0'/0/0", "Keplr Injective coin type 60", "bip_utils Injective", "BIP-39 12-word vector with passphrase TREZOR", family_seed_bip39_12_trezor, "inj1nse0w82dhraeuxjckz5qmauexhnj2maxq4dw8a", "inj1nse0w82dhraeuxjckz5qmauexhnj2maxq4dw8a"},
    {FAM_VET, "VET", "m/44'/818'/0'/0/0", "Trust Wallet Wallet Core default", "bip_utils VeChain", "BIP-39 12-word vector with passphrase TREZOR", family_seed_bip39_12_trezor, "0x3b13Adb72fC1009347FC6058417A97171CA1Cf7D", "0x3b13Adb72fC1009347FC6058417A97171CA1Cf7D"},
    {FAM_BCH, "BCH", "m/44'/145'/0'/0/0", "Trust Wallet default", "bip_utils Bitcoin Cash", "BIP-39 12-word vector with passphrase TREZOR", family_seed_bip39_12_trezor, "bitcoincash:qpmtwknkc0zfk0j8v6e6p8rye6q48de85stk6qcprd", "bitcoincash:qpmtwknkc0zfk0j8v6e6p8rye6q48de85stk6qcprd"},
    {FAM_ZEC, "ZEC", "m/44'/133'/0'/0/0", "Exodus transparent t-address path", "bip_utils Zcash", "BIP-39 12-word vector with passphrase TREZOR", family_seed_bip39_12_trezor, "t1eB9Q9aDobjEnazefA9hdGyx3ku7dHshw5", "t1eB9Q9aDobjEnazefA9hdGyx3ku7dHshw5"},
    {FAM_XLM, "XLM", "m/44'/148'/0'", "Freighter / Stellar SEP-0005 account path", "bip_utils Stellar", "BIP-39 12-word vector with passphrase TREZOR", family_seed_bip39_12_trezor, "GBXISQLLM6OGWWZU7SCNF2GOJSQLHJU3I76P23J6IDSJGKEEGM2AJYG5", "GBXISQLLM6OGWWZU7SCNF2GOJSQLHJU3I76P23J6IDSJGKEEGM2AJYG5"},
    {FAM_NEAR, "NEAR", "m/44'/397'/0'", "SafePal NEAR path", "bip_utils NEAR Protocol", "BIP-39 12-word vector with passphrase TREZOR", family_seed_bip39_12_trezor, "12bce054414d9a5980a8218b135474a752e8139099b2ff019f29293ae220fa0e", "12bce054414d9a5980a8218b135474a752e8139099b2ff019f29293ae220fa0e"},
    {FAM_APT, "APT", "m/44'/637'/0'/0'/0'", "Petra-compatible Aptos Ed25519 path", "bip_utils Aptos", "BIP-39 12-word vector with passphrase TREZOR", family_seed_bip39_12_trezor, "0x53718253374d489c65ee9447c6c944880388e5168d8da2ae5e7c3ea69e049a1c", "0x53718253374d489c65ee9447c6c944880388e5168d8da2ae5e7c3ea69e049a1c"},
    {FAM_SUI, "SUI", "m/44'/784'/0'/0'/0'", "Sui Wallet Ed25519 path", "bip_utils Sui", "BIP-39 12-word vector with passphrase TREZOR", family_seed_bip39_12_trezor, "0x85614bb760547968e07addd47db5e08c7bebf1e2ed248ff37d9d0ed01b395383", "0x85614bb760547968e07addd47db5e08c7bebf1e2ed248ff37d9d0ed01b395383"},
};
static const size_t family_address_fixture_count =
    sizeof(family_address_fixtures) / sizeof(family_address_fixtures[0]);
