#!/usr/bin/env python3
"""
Generate src/coin_catalog.h from tools/coin_catalog.json (curated, established coins only).

Each coin carries: wallet family (how its address is derived), network label, token
contract (EVM/SPL/TRC-20), category, brand colours and an LED rhythm derived from how its
chain actually produces blocks (proof-of-work heartbeat, PoS slot breathing, fast-chain
shimmer, consensus-ledger ripple, steady glow for stablecoins, sparkle for meme coins).

  python3 tools/gen_coin_catalog.py
"""
import colorsys
import hashlib
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
FAMILIES = ["BTC", "EVM", "SOL", "DOGE", "LTC", "TRX", "XRP", "ATOM", "INJ", "XLM", "NEAR", "APT", "VET", "BCH", "SUI", "ZEC"]
CATEGORIES = ["CRYPTO", "STABLE", "MEME"]

# Block / slot / ledger interval per network (ms) and how blocks are produced
NETWORK_RHYTHM = {
    "Bitcoin": (600000, "POW"), "Bitcoin Cash": (600000, "POW"), "Litecoin": (150000, "POW"),
    "Zcash t-addr": (75000, "POW"), "Dogecoin": (60000, "POW"),
    "Ethereum": (12000, "SLOT"), "ERC-20 (ETH)": (12000, "SLOT"), "VeChain": (10000, "SLOT"),
    "Cosmos Hub": (6000, "SLOT"),
    "XRP Ledger": (4000, "LEDGER"), "Stellar": (5000, "LEDGER"),
    "TRON": (3000, "SLOT"), "TRC-20 (TRON)": (3000, "SLOT"),
    "Base": (2000, "SHIMMER"), "Optimism": (2000, "SHIMMER"), "Polygon": (2000, "SHIMMER"),
    "Avalanche C": (2000, "SHIMMER"), "Mantle": (2000, "SHIMMER"), "BNB Chain": (1500, "SHIMMER"),
    "BEP-20 (BSC)": (1500, "SHIMMER"), "NEAR": (1000, "SHIMMER"), "Injective": (700, "SHIMMER"),
    "Solana": (400, "SHIMMER"), "SPL (Solana)": (400, "SHIMMER"), "Sui": (400, "SHIMMER"),
    "Arbitrum": (250, "SHIMMER"), "Aptos": (250, "SHIMMER"),
}
PATTERNS = ["POW", "SLOT", "LEDGER", "SHIMMER", "STEADY"]
# Signature two-colour gradients where the brand has one
GRADIENT2 = {"SOL": (20, 241, 149), "ETH": (138, 75, 255)}


def hue_shift(rgb, deg):
    h, l, s = colorsys.rgb_to_hls(*(c / 255 for c in rgb))
    r, g, b = colorsys.hls_to_rgb((h + deg / 360) % 1, l, s)
    return tuple(int(round(c * 255)) for c in (r, g, b))


def fallback_rgb(symbol):
    h = int(hashlib.sha256(symbol.encode()).hexdigest(), 16) % 360
    r, g, b = colorsys.hls_to_rgb(h / 360, 0.55, 0.85)
    return (int(r * 255), int(g * 255), int(b * 255))


def c_str(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def main():
    coins = json.load(open(os.path.join(HERE, "coin_catalog.json")))
    palette = {}
    for line in open(os.path.join(HERE, "coin_palette.txt")):
        p = line.split()
        if len(p) == 4:
            palette[p[0]] = tuple(int(x) for x in p[1:])
    rows = []
    for c in coins:
        rgb = palette.get(c["symbol"]) or (tuple(c["rgb"]) if c.get("rgb") else fallback_rgb(c["symbol"]))
        rgb2 = GRADIENT2.get(c["symbol"]) or hue_shift(rgb, 40)
        block_ms, pattern = NETWORK_RHYTHM[c["network"]]
        if c["category"] == "STABLE":
            pattern = "STEADY"
        rows.append((c, rgb, rgb2, block_ms, pattern))

    out = ["// AUTO-GENERATED by tools/gen_coin_catalog.py from tools/coin_catalog.json — do not edit.",
           "#pragma once", "#include <stdint.h>", "",
           "enum WalletFamily : uint8_t { " + ", ".join(f"FAM_{f}" for f in FAMILIES) + ", FAM_COUNT };",
           "enum CoinCategory : uint8_t { " + ", ".join(f"CAT_{k}" for k in CATEGORIES) + " };",
           "enum LedPattern : uint8_t { " + ", ".join(f"LEDP_{p}" for p in PATTERNS) + " };", "",
           "struct CatalogCoin {",
           "    const char* symbol;", "    const char* name;", "    const char* cgId;      // CoinGecko id",
           "    const char* network;   // chain label shown on receive screens",
           "    const char* contract;  // token contract / mint (\"\" for native coins)",
           "    WalletFamily family;", "    CoinCategory category;",
           "    uint8_t r, g, b;       // brand colour", "    uint8_t r2, g2, b2;    // secondary (shimmer / gradient)",
           "    LedPattern pattern;", "    uint32_t blockMs;      // chain block / slot / ledger interval",
           "};", "", f"#define CATALOG_COUNT {len(rows)}", "",
           "static const CatalogCoin CATALOG[CATALOG_COUNT] = {"]
    for c, rgb, rgb2, block_ms, pattern in rows:
        out.append(f"    {{{c_str(c['symbol'])}, {c_str(c['name'])}, {c_str(c['cg'])}, {c_str(c['network'])}, "
                   f"{c_str(c['contract'])}, FAM_{c['family']}, CAT_{c['category']}, "
                   f"{rgb[0]}, {rgb[1]}, {rgb[2]}, {rgb2[0]}, {rgb2[1]}, {rgb2[2]}, LEDP_{pattern}, {block_ms}}},")
    out.append("};")
    out.append("")
    dst = os.path.join(HERE, "..", "src", "coin_catalog.h")
    open(dst, "w").write("\n".join(out))
    print(f"wrote {dst}: {len(rows)} coins")


if __name__ == "__main__":
    main()
