// AUTO-GENERATED by tools/gen_coin_catalog.py from tools/coin_catalog.json — do not edit.
#pragma once
#include <stdint.h>

enum WalletFamily : uint8_t { FAM_BTC, FAM_EVM, FAM_SOL, FAM_DOGE, FAM_LTC, FAM_TRX, FAM_XRP, FAM_ATOM, FAM_INJ, FAM_XLM, FAM_NEAR, FAM_APT, FAM_VET, FAM_BCH, FAM_SUI, FAM_ZEC, FAM_COUNT };
enum CoinCategory : uint8_t { CAT_CRYPTO, CAT_STABLE, CAT_MEME };
enum LedPattern : uint8_t { LEDP_POW, LEDP_SLOT, LEDP_LEDGER, LEDP_SHIMMER, LEDP_STEADY };

struct CatalogCoin {
    const char* symbol;
    const char* name;
    const char* cgId;      // CoinGecko id
    const char* network;   // chain label shown on receive screens
    const char* contract;  // token contract / mint ("" for native coins)
    WalletFamily family;
    CoinCategory category;
    uint8_t r, g, b;       // brand colour
    uint8_t r2, g2, b2;    // secondary (shimmer / gradient)
    LedPattern pattern;
    uint32_t blockMs;      // chain block / slot / ledger interval
};

#define CATALOG_COUNT 88

static const CatalogCoin CATALOG[CATALOG_COUNT] = {
    {"BTC", "Bitcoin", "bitcoin", "Bitcoin", "", FAM_BTC, CAT_CRYPTO, 247, 147, 26, 200, 247, 26, LEDP_POW, 600000},
    {"ETH", "Ethereum", "ethereum", "Ethereum", "", FAM_EVM, CAT_CRYPTO, 98, 126, 234, 138, 75, 255, LEDP_SLOT, 12000},
    {"BNB", "BNB", "binancecoin", "BNB Chain", "", FAM_EVM, CAT_CRYPTO, 243, 186, 47, 169, 243, 47, LEDP_SHIMMER, 1500},
    {"XRP", "XRP", "ripple", "XRP Ledger", "", FAM_XRP, CAT_CRYPTO, 0, 120, 230, 33, 0, 230, LEDP_LEDGER, 4000},
    {"SOL", "Solana", "solana", "Solana", "", FAM_SOL, CAT_CRYPTO, 20, 241, 149, 20, 241, 149, LEDP_SHIMMER, 400},
    {"TRX", "TRON", "tron", "TRON", "", FAM_TRX, CAT_CRYPTO, 210, 15, 15, 210, 145, 15, LEDP_SLOT, 3000},
    {"ZEC", "Zcash", "zcash", "Zcash t-addr", "", FAM_ZEC, CAT_CRYPTO, 245, 183, 40, 170, 245, 40, LEDP_POW, 75000},
    {"LINK", "Chainlink", "chainlink", "ERC-20 (ETH)", "0x514910771af9ca656af840dff83e8264ecf986ca", FAM_EVM, CAT_CRYPTO, 43, 110, 245, 111, 43, 245, LEDP_SLOT, 12000},
    {"LEO", "LEO Token", "leo-token", "ERC-20 (ETH)", "0x2af5d2ad76741191d15dfe7bf6ac92d4bd912ca3", FAM_EVM, CAT_CRYPTO, 193, 166, 72, 139, 193, 72, LEDP_SLOT, 12000},
    {"XLM", "Stellar", "stellar", "Stellar", "", FAM_XLM, CAT_CRYPTO, 15, 135, 195, 15, 15, 195, LEDP_LEDGER, 5000},
    {"BCH", "Bitcoin Cash", "bitcoin-cash", "Bitcoin Cash", "", FAM_BCH, CAT_CRYPTO, 10, 193, 142, 10, 122, 193, LEDP_POW, 600000},
    {"UNI", "Uniswap", "uniswap", "ERC-20 (ETH)", "0x1f9840a85d5af5bf1d1762f925bdaddc4201f984", FAM_EVM, CAT_CRYPTO, 255, 4, 180, 255, 4, 13, LEDP_SLOT, 12000},
    {"NEAR", "NEAR Protocol", "near", "NEAR", "", FAM_NEAR, CAT_CRYPTO, 0, 236, 151, 0, 164, 236, LEDP_SHIMMER, 1000},
    {"LTC", "Litecoin", "litecoin", "Litecoin", "", FAM_LTC, CAT_CRYPTO, 175, 180, 185, 177, 175, 185, LEDP_POW, 150000},
    {"AVAX", "Avalanche", "avalanche-2", "Avalanche C", "", FAM_EVM, CAT_CRYPTO, 232, 65, 66, 232, 175, 65, LEDP_SHIMMER, 2000},
    {"SUI", "Sui", "sui", "Sui", "", FAM_SUI, CAT_CRYPTO, 77, 162, 255, 111, 77, 255, LEDP_SHIMMER, 400},
    {"CRO", "Cronos", "crypto-com-chain", "ERC-20 (ETH)", "0xa0b73e1ff0b80914ab6fe0444e65848c4c34450b", FAM_EVM, CAT_CRYPTO, 6, 37, 100, 38, 6, 100, LEDP_SLOT, 12000},
    {"XAUT", "Tether Gold", "tether-gold", "ERC-20 (ETH)", "0x68749665ff8d2d112fa859aa293f07a622782f38", FAM_EVM, CAT_CRYPTO, 212, 178, 91, 165, 212, 91, LEDP_SLOT, 12000},
    {"OKB", "OKB", "okb", "ERC-20 (ETH)", "0x75231f58b43240c9718dd58b4967c5114342a86c", FAM_EVM, CAT_CRYPTO, 0, 229, 255, 0, 59, 255, LEDP_SLOT, 12000},
    {"MNT", "Mantle", "mantle", "Mantle", "", FAM_EVM, CAT_CRYPTO, 88, 145, 126, 88, 126, 145, LEDP_SHIMMER, 2000},
    {"AAVE", "Aave", "aave", "ERC-20 (ETH)", "0x7fc66500c84a76ad7e9c93437bfc5ac33e2ddae9", FAM_EVM, CAT_CRYPTO, 148, 146, 247, 215, 146, 247, LEDP_SLOT, 12000},
    {"ENA", "Ethena", "ethena", "ERC-20 (ETH)", "0x57e114b691db790c35207b2e685d4a43181e6061", FAM_EVM, CAT_CRYPTO, 0, 229, 255, 0, 59, 255, LEDP_SLOT, 12000},
    {"ONDO", "Ondo", "ondo-finance", "ERC-20 (ETH)", "0xfaba6f8e4a5e8ab82f62fe7c39859fa577269be3", FAM_EVM, CAT_CRYPTO, 0, 229, 255, 0, 59, 255, LEDP_SLOT, 12000},
    {"MORPHO", "Morpho", "morpho", "ERC-20 (ETH)", "0x58d97b57bb95320f9a05dc918aef65434969c2b2", FAM_EVM, CAT_CRYPTO, 40, 115, 254, 108, 40, 254, LEDP_SLOT, 12000},
    {"PAXG", "PAX Gold", "pax-gold", "ERC-20 (ETH)", "0x45804880de22913dafe09f4980848ece6ecbaf78", FAM_EVM, CAT_CRYPTO, 221, 190, 21, 119, 221, 21, LEDP_SLOT, 12000},
    {"SKY", "Sky", "sky", "ERC-20 (ETH)", "0x56072c95faa701256059aa122697b133aded9279", FAM_EVM, CAT_CRYPTO, 54, 205, 248, 54, 76, 248, LEDP_SLOT, 12000},
    {"WLD", "Worldcoin", "worldcoin-wld", "ERC-20 (ETH)", "0x163f8c2467924be0ae7b5347228cabf260318753", FAM_EVM, CAT_CRYPTO, 0, 229, 255, 0, 59, 255, LEDP_SLOT, 12000},
    {"ARB", "Arbitrum", "arbitrum", "Arbitrum", "0x912ce59144191c1204e64559fe8253a0e49e6548", FAM_EVM, CAT_CRYPTO, 18, 120, 240, 64, 18, 240, LEDP_SHIMMER, 250},
    {"BGB", "Bitget Token", "bitget-token", "ERC-20 (ETH)", "0x54d2252757e1672eead234d27b1270728ff90581", FAM_EVM, CAT_CRYPTO, 0, 235, 248, 0, 70, 248, LEDP_SLOT, 12000},
    {"GT", "Gate", "gatechain-token", "ERC-20 (ETH)", "0xe66747a101bff2dba3697199dcce5b743b454759", FAM_EVM, CAT_CRYPTO, 11, 99, 254, 85, 11, 254, LEDP_SLOT, 12000},
    {"POL", "POL (ex-MATIC)", "polygon-ecosystem-token", "Polygon", "", FAM_EVM, CAT_CRYPTO, 130, 71, 229, 229, 71, 223, LEDP_SHIMMER, 2000},
    {"QNT", "Quant", "quant-network", "ERC-20 (ETH)", "0x4a220e6096b25eadb88358cb44068a3248254675", FAM_EVM, CAT_CRYPTO, 0, 229, 255, 0, 59, 255, LEDP_SLOT, 12000},
    {"JUP", "Jupiter", "jupiter-exchange-solana", "SPL (Solana)", "JUPyiwrYJFskUPiHa7hkeR8VUtAeFoSYbKedZNsDvCN", FAM_SOL, CAT_CRYPTO, 57, 184, 186, 57, 98, 186, LEDP_SHIMMER, 400},
    {"RENDER", "Render", "render-token", "ERC-20 (ETH)", "0x6de037ef9ad2725eb40118bb1702ebb27e4aeb24", FAM_EVM, CAT_CRYPTO, 208, 23, 24, 208, 145, 23, LEDP_SLOT, 12000},
    {"ATOM", "Cosmos Hub", "cosmos", "Cosmos Hub", "", FAM_ATOM, CAT_CRYPTO, 60, 65, 145, 112, 60, 145, LEDP_SLOT, 6000},
    {"JST", "JUST", "just", "TRC-20 (TRON)", "TCFLL5dx5ZJdKnWuesXxi1VPwjLVmWZZy9", FAM_TRX, CAT_CRYPTO, 179, 29, 28, 179, 130, 28, LEDP_SLOT, 3000},
    {"NEXO", "NEXO", "nexo", "ERC-20 (ETH)", "0xb62132e35a6c13ee1ee0f84dc5d40bad8d815206", FAM_EVM, CAT_CRYPTO, 228, 219, 202, 220, 228, 202, LEDP_SLOT, 12000},
    {"CAKE", "PancakeSwap", "pancakeswap-token", "BEP-20 (BSC)", "0x0e09fabb73bd3ade0a17ecc321fd13a19e81ce82", FAM_EVM, CAT_CRYPTO, 180, 113, 59, 166, 180, 59, LEDP_SHIMMER, 1500},
    {"VET", "VeChain", "vechain", "VeChain", "", FAM_VET, CAT_CRYPTO, 32, 205, 250, 32, 60, 250, LEDP_SLOT, 10000},
    {"INJ", "Injective", "injective-protocol", "Injective", "", FAM_INJ, CAT_CRYPTO, 0, 245, 255, 0, 75, 255, LEDP_SHIMMER, 700},
    {"AERO", "Aerodrome Finance", "aerodrome-finance", "Base", "0x940181a94a35a4569e4529a3cdfb74e38fd98631", FAM_EVM, CAT_CRYPTO, 88, 115, 234, 158, 88, 234, LEDP_SHIMMER, 2000},
    {"APT", "Aptos", "aptos", "Aptos", "", FAM_APT, CAT_CRYPTO, 45, 216, 167, 45, 151, 216, LEDP_SHIMMER, 250},
    {"ETHFI", "Ether.fi", "ether-fi", "ERC-20 (ETH)", "0xfe0c30065b384f05761f15d0cc899d4f9f9cc0eb", FAM_EVM, CAT_CRYPTO, 24, 28, 110, 77, 24, 110, LEDP_SLOT, 12000},
    {"RAY", "Raydium", "raydium", "SPL (Solana)", "4k3Dyjzvzp8eMZWUXbBCjEvwSkkk59S5iCNLY3QrkX6R", FAM_SOL, CAT_CRYPTO, 22, 33, 67, 41, 22, 67, LEDP_SHIMMER, 400},
    {"ZRO", "LayerZero", "layerzero", "ERC-20 (ETH)", "0x6985884c4392d348587b19cb9eaaf157f13271cd", FAM_EVM, CAT_CRYPTO, 0, 229, 255, 0, 59, 255, LEDP_SLOT, 12000},
    {"CRV", "Curve DAO", "curve-dao-token", "ERC-20 (ETH)", "0xd533a949740bb3306d119cc777fa900ba034cd52", FAM_EVM, CAT_CRYPTO, 197, 7, 1, 197, 138, 1, LEDP_SLOT, 12000},
    {"PYTH", "Pyth Network", "pyth-network", "SPL (Solana)", "HZ1JovNiVvGrGNiiYvEozEVgZ58xaU3RKwX8eACQBCt3", FAM_SOL, CAT_CRYPTO, 210, 199, 231, 231, 199, 231, LEDP_SHIMMER, 400},
    {"FET", "Artificial Superintell", "fetch-ai", "ERC-20 (ETH)", "0xaea46a60368a7bd060eec7df8cba43b7ef41ad85", FAM_EVM, CAT_CRYPTO, 0, 229, 255, 0, 59, 255, LEDP_SLOT, 12000},
    {"PENDLE", "Pendle", "pendle", "ERC-20 (ETH)", "0x808507121b80c02388fad14726482e061b8da827", FAM_EVM, CAT_CRYPTO, 29, 62, 111, 51, 29, 111, LEDP_SLOT, 12000},
    {"BTT", "BitTorrent", "bittorrent", "TRC-20 (TRON)", "TAFjULxiVgT4qWk6UZwjqwZXTSaGaqnVp4", FAM_TRX, CAT_CRYPTO, 0, 229, 255, 0, 59, 255, LEDP_SLOT, 3000},
    {"SUN", "Sun Token", "sun-token", "TRC-20 (TRON)", "TSSMHYeV2uE9qYH95DqyoCuNCzEL1NvU3S", FAM_TRX, CAT_CRYPTO, 251, 181, 112, 228, 251, 112, LEDP_SLOT, 3000},
    {"LDO", "Lido DAO", "lido-dao", "ERC-20 (ETH)", "0x5a98fcbea516cf06857215779fd812ca3bef1b32", FAM_EVM, CAT_CRYPTO, 234, 138, 134, 234, 205, 134, LEDP_SLOT, 12000},
    {"OHM", "Olympus", "olympus", "ERC-20 (ETH)", "0x64aa3364f17a4d01c6f1751fd97c2bd3d7e7f1d5", FAM_EVM, CAT_CRYPTO, 0, 229, 255, 0, 59, 255, LEDP_SLOT, 12000},
    {"GNO", "Gnosis", "gnosis", "ERC-20 (ETH)", "0x6810e776880c02933d47db1b9fc05908e5386b96", FAM_EVM, CAT_CRYPTO, 20, 35, 53, 27, 20, 53, LEDP_SLOT, 12000},
    {"STRK", "Starknet", "starknet", "ERC-20 (ETH)", "0xca14007eff0db1f8135f4c25b34de49ab0d42766", FAM_EVM, CAT_CRYPTO, 10, 11, 78, 54, 10, 78, LEDP_SLOT, 12000},
    {"USDT", "Tether", "tether", "ERC-20 (ETH)", "0xdac17f958d2ee523a2206206994597c13d831ec7", FAM_EVM, CAT_STABLE, 9, 151, 151, 9, 56, 151, LEDP_STEADY, 12000},
    {"USDC", "USDC", "usd-coin", "ERC-20 (ETH)", "0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48", FAM_EVM, CAT_STABLE, 20, 89, 193, 66, 20, 193, LEDP_STEADY, 12000},
    {"USDS", "USDS", "usds", "ERC-20 (ETH)", "0xdc035d45d973e3ec169d2276ddab16f1e407384f", FAM_EVM, CAT_STABLE, 237, 42, 205, 237, 42, 75, LEDP_STEADY, 12000},
    {"USDE", "Ethena USDe", "ethena-usde", "ERC-20 (ETH)", "0x4c9edd5852cd905f086c759e8383e09bff1e68b3", FAM_EVM, CAT_STABLE, 237, 42, 198, 237, 42, 68, LEDP_STEADY, 12000},
    {"DAI", "Dai", "dai", "ERC-20 (ETH)", "0x6b175474e89094c44da98b954eedeac495271d0f", FAM_EVM, CAT_STABLE, 250, 187, 56, 184, 250, 56, LEDP_STEADY, 12000},
    {"PYUSD", "PayPal USD", "paypal-usd", "ERC-20 (ETH)", "0x6c3ea9036406852006290770bedfcaba0e23a0e8", FAM_EVM, CAT_STABLE, 49, 237, 42, 42, 237, 165, LEDP_STEADY, 12000},
    {"TUSD", "TrueUSD", "true-usd", "ERC-20 (ETH)", "0x0000000000085d4780b73119b644ae5ecd22b376", FAM_EVM, CAT_STABLE, 237, 42, 185, 237, 42, 55, LEDP_STEADY, 12000},
    {"EURC", "EURC", "euro-coin", "ERC-20 (ETH)", "0x1abaea1f7c830bd89acc67ec4af516284b1bc33c", FAM_EVM, CAT_STABLE, 42, 185, 237, 42, 55, 237, LEDP_STEADY, 12000},
    {"FDUSD", "First Digital USD", "first-digital-usd", "ERC-20 (ETH)", "0xc5f0f7b66764f6ec8c8dff7ba683102295e16409", FAM_EVM, CAT_STABLE, 237, 45, 42, 237, 175, 42, LEDP_STEADY, 12000},
    {"DOGE", "Dogecoin", "dogecoin", "Dogecoin", "", FAM_DOGE, CAT_MEME, 205, 165, 40, 135, 205, 40, LEDP_POW, 60000},
    {"SHIB", "Shiba Inu", "shiba-inu", "ERC-20 (ETH)", "0x95ad61b0a150d79219dcf64e1e6cc01f0b64c4ce", FAM_EVM, CAT_MEME, 225, 75, 0, 225, 225, 0, LEDP_SLOT, 12000},
    {"PUMP", "Pump.fun", "pump-fun", "SPL (Solana)", "pumpCmXqMfrsAkQ5r49WcJnRayYRqmXz6ae8H7H9Dfn", FAM_SOL, CAT_MEME, 79, 199, 139, 79, 179, 199, LEDP_SHIMMER, 400},
    {"PEPE", "Pepe", "pepe", "ERC-20 (ETH)", "0x6982508145454ce325ddbe47a25d4ec3d2311933", FAM_EVM, CAT_MEME, 0, 200, 50, 0, 200, 183, LEDP_SLOT, 12000},
    {"PENGU", "Pudgy Penguins", "pudgy-penguins", "SPL (Solana)", "2zMMhcVQEXDtdE6vsFS7S7D5oUodfJHE8vd1gnBouauv", FAM_SOL, CAT_MEME, 137, 174, 244, 171, 137, 244, LEDP_SHIMMER, 400},
    {"TRUMP", "Official Trump", "official-trump", "SPL (Solana)", "6p6xgHyF7AeE6TZkSmFsko444wqoP15icUSqi2jfGiPN", FAM_SOL, CAT_MEME, 218, 199, 135, 182, 218, 135, LEDP_SHIMMER, 400},
    {"SPX", "SPX6900", "spx6900", "ERC-20 (ETH)", "0xe0f63a424a4439cbe457d80e4f4b51ad25b2c56c", FAM_EVM, CAT_MEME, 217, 174, 72, 163, 217, 72, LEDP_SLOT, 12000},
    {"BONK", "Bonk", "bonk", "SPL (Solana)", "DezXAZ8z7PnrnRJjz3wXBoRgixCa6xjnB7YaB1pPB263", FAM_SOL, CAT_MEME, 255, 140, 0, 200, 255, 0, LEDP_SHIMMER, 400},
    {"FLOKI", "FLOKI", "floki", "ERC-20 (ETH)", "0xcf0c122c6b73ff809c693db761e7baebe62b6a2e", FAM_EVM, CAT_MEME, 215, 130, 15, 167, 215, 15, LEDP_SLOT, 12000},
    {"WIF", "dogwifhat", "dogwifcoin", "SPL (Solana)", "EKpQGSJtjMFqKZ9KQanSqYXRcF8fBopzLHYxdM65zcjm", FAM_SOL, CAT_MEME, 201, 122, 86, 201, 199, 86, LEDP_SHIMMER, 400},
    {"FARTCOIN", "Fartcoin", "fartcoin", "SPL (Solana)", "9BB6NFEcjBCtnNLFko2FqVQBq8HHM13kCyYcdQbgpump", FAM_SOL, CAT_MEME, 0, 229, 255, 0, 59, 255, LEDP_SHIMMER, 400},
    {"CHEEMS", "Cheems Token", "cheems-token", "BEP-20 (BSC)", "0x0df0587216a4a1bb7d5082fdc491d93d2dd4b413", FAM_EVM, CAT_MEME, 124, 92, 58, 112, 124, 58, LEDP_SHIMMER, 1500},
    {"MELANIA", "Melania Meme", "melania-meme", "SPL (Solana)", "FUAfBo2jgks6gB4Z4LfZkqSZgzNucisEHqnNebaRxM1P", FAM_SOL, CAT_MEME, 0, 229, 255, 0, 59, 255, LEDP_SHIMMER, 400},
    {"BOME", "BOOK OF MEME", "book-of-meme", "SPL (Solana)", "ukHH6c7mMyiWCf1b9pnWe25TSpkDDt3H5pQZgZ74J82", FAM_SOL, CAT_MEME, 82, 132, 45, 45, 132, 66, LEDP_SHIMMER, 400},
    {"BABYDOGE", "Baby Doge Coin", "baby-doge-coin", "BEP-20 (BSC)", "0xc748673057861a797275cd8a068abb95a902e8de", FAM_EVM, CAT_MEME, 250, 217, 74, 166, 250, 74, LEDP_SHIMMER, 1500},
    {"TURBO", "Turbo", "turbo", "ERC-20 (ETH)", "0xa35923162c49cf95e6bf26623385eb431ad920d3", FAM_EVM, CAT_MEME, 245, 50, 0, 245, 213, 0, LEDP_SLOT, 12000},
    {"POPCAT", "Popcat", "popcat", "SPL (Solana)", "7GCihgDB8fe6KNjn2MYtkzZcRjQy3t9GHdC8uHYmW2hr", FAM_SOL, CAT_MEME, 255, 128, 171, 255, 170, 128, LEDP_SHIMMER, 400},
    {"PNUT", "Peanut the Squirrel", "peanut-the-squirrel", "SPL (Solana)", "2qEHjDLDLbuBgRYvsxhc5D6uDWAivNFZGan56P1tpump", FAM_SOL, CAT_MEME, 124, 174, 216, 135, 124, 216, LEDP_SHIMMER, 400},
    {"BRETT", "Brett", "based-brett", "Base", "0x532f27101965dd16442e59d40670faf5ebb142e4", FAM_EVM, CAT_MEME, 0, 82, 255, 88, 0, 255, LEDP_SHIMMER, 2000},
    {"TOSHI", "Toshi", "toshi", "Base", "0xac1bd2486aaf3b5c0fc3fd868558b082a531b2b4", FAM_EVM, CAT_MEME, 6, 83, 248, 90, 6, 248, LEDP_SHIMMER, 2000},
    {"MOG", "Mog Coin", "mog-coin", "ERC-20 (ETH)", "0xaaee1a9723aadb7afa2810263653a34ba2c21c7a", FAM_EVM, CAT_MEME, 176, 38, 255, 255, 38, 189, LEDP_SLOT, 12000},
    {"PEOPLE", "ConstitutionDAO", "constitutiondao", "ERC-20 (ETH)", "0x7a58c0be72be218b41c608b7fe7c5bb630736c71", FAM_EVM, CAT_MEME, 206, 179, 115, 172, 206, 115, LEDP_SLOT, 12000},
    {"MOODENG", "Moo Deng", "moo-deng", "SPL (Solana)", "ED5nyyWEzpPPiWimP8vYm7sD7TD3LAt3Q3gRTWHzPJBY", FAM_SOL, CAT_MEME, 55, 107, 161, 74, 55, 161, LEDP_SHIMMER, 400},
    {"MEME", "MEMETOON", "memetoon", "BEP-20 (BSC)", "0x193397bb76868c6873e733ad60d5953843ebc84e", FAM_EVM, CAT_MEME, 220, 248, 165, 165, 248, 165, LEDP_SHIMMER, 1500},
};
