/**
 * crypto_coins.h — Portfolio registry over the curated coin catalog
 * ==============================================================================
 * One CoinAsset per entry of CATALOG (src/coin_catalog.h, generated by
 * tools/gen_coin_catalog.py): wallet family, network, contract, colours and LED
 * rhythm come from the catalog; enabled/balance/price are runtime state.
 * Only enabled coins get a receive address, a price feed, a UI card and an LED.
 */

#pragma once

#include <Arduino.h>
#include "coin_catalog.h"
#include "wallet_families.h"

typedef uint8_t SupportedCoinId;          // index into CATALOG
#define COIN_REGISTRY_COUNT CATALOG_COUNT

// A price older than this is shown as stale
#define PRICE_STALE_MS (15UL * 60UL * 1000UL)

struct CoinAsset {
    SupportedCoinId     id;
    const CatalogCoin*  meta;
    const char*         symbol;
    const char*         name;
    bool                enabled;           // selected in the setup page
    float               balance;           // holding, from the host daemon / wall ticker
    float               priceUsd;          // 0 until a live price arrives
    float               change24h;
    uint32_t            priceUpdatedMs;    // millis() of the last live price, 0 = never
    char                address[FAMILY_ADDR_LEN];   // receive address of the coin's wallet family
};

class CryptoCoinRegistry {
public:
    static void init();
    static int getCoinCount() { return COIN_REGISTRY_COUNT; }
    static CoinAsset* getCoin(SupportedCoinId id);
    static CoinAsset* getCoinByIndex(int index) { return getCoin((SupportedCoinId)index); }
    static CoinAsset* findBySymbol(const char* symbol);
    static int getActiveCoinCount();
    static CoinAsset* getActiveCoinByIndex(int activeIdx);
    static int getCountByCategory(CoinCategory cat);
    static bool isFamilyInUse(WalletFamily fam);   // any enabled coin on this wallet family
    static void setCoinEnabled(SupportedCoinId id, bool enabled);
    static void updateBalance(SupportedCoinId id, float balance);
    static void updatePrice(SupportedCoinId id, float priceUsd, float change24h);
    static bool hasLivePrice(const CoinAsset* c) { return c && c->priceUpdatedMs != 0; }
    static bool isPriceStale(const CoinAsset* c) {
        return !hasLivePrice(c) || millis() - c->priceUpdatedMs > PRICE_STALE_MS;
    }
    static float getTotalPortfolioValueUsd();

    // Persistence (NVS "portfolio_v2", keyed by symbol)
    static void savePreferences();
    static void loadPreferences();

private:
    static CoinAsset _coins[COIN_REGISTRY_COUNT];
};
